# ==============================================================================
# LaTeX Resume Tailorer — Authentication API Router
# ==============================================================================
# This router implements HTTP endpoints for user registration and login.
# JWT access tokens are signed using a HS256 secret key.
# ==============================================================================

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordRequestForm
from sqlalchemy.orm import Session

from backend.database import get_db
from backend.models import User, AuditLog
from backend.schemas import UserRegister, UserOut, Token
from backend.auth import get_password_hash, verify_password, create_access_token

router = APIRouter(prefix="/auth", tags=["Authentication"])

@router.post("/register", response_model=UserOut, status_code=status.HTTP_201_CREATED)
def register_user(payload: UserRegister, db: Session = Depends(get_db)):
    """
    Registers a new user account:
    1. Checks if the email address is already registered in our database.
    2. Hashes the password securely via bcrypt.
    3. Saves the User object to PostgreSQL.
    4. Writes an AuditLog record of the registration action.
    """
    # Check if a user with this email already exists
    existing_user = db.query(User).filter(User.email == payload.email).first()
    if existing_user:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Email address is already registered."
        )
        
    # Securely hash the password (never store plaintext)
    hashed_pwd = get_password_hash(payload.password)
    
    # Instantiate the new User model
    new_user = User(
        email=payload.email,
        hashed_password=hashed_pwd
    )
    
    # Save user to Postgres
    db.add(new_user)
    db.commit()
    db.refresh(new_user) # Reload ID field generated by database
    
    # Record registration in the AuditLog (anonymized payload)
    log_entry = AuditLog(
        user_id=new_user.id,
        action="register"
    )
    db.add(log_entry)
    db.commit()
    
    return new_user

@router.post("/login", response_model=Token)
def login_user(payload: OAuth2PasswordRequestForm = Depends(), db: Session = Depends(get_db)):
    """
    Authenticates user credentials and issues a JWT token.
    FastAPI expects 'username' and 'password' fields (OAuth2 standard).
    We map 'username' to the user's email address.
    """
    # Retrieve user account from database
    user = db.query(User).filter(User.email == payload.username).first()
    
    # If user doesn't exist OR password validation fails, throw HTTP 401
    # Note: We return a generic error message so we don't leak user existence
    if not user or not verify_password(payload.password, user.hashed_password):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid email or password.",
            headers={"WWW-Authenticate": "Bearer"},
        )
        
    # Generate a secure JWT access token
    access_token = create_access_token(data={"sub": user.email})
    
    # Record successful login in the AuditLog
    log_entry = AuditLog(
        user_id=user.id,
        action="login"
    )
    db.add(log_entry)
    db.commit()
    
    return {"access_token": access_token, "token_type": "bearer"}
