# ==============================================================================
# LaTeX Resume Tailorer — Configuration Engine
# ==============================================================================
# This module loads all configuration variables from the environment or a local
# '.env' file using Pydantic Settings. Default values are provided for local
# Docker development.
# ==============================================================================

import os
from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict

class Settings(BaseSettings):
    """
    Application-wide settings loader. Loads environment variables automatically
    and parses types (e.g. integer expirations, float values).
    """

    # --------------------------------------------------------------------------
    # Database Settings
    # --------------------------------------------------------------------------
    # Connects to PostgreSQL. 'db' matches the service name in docker-compose.yml.
    DATABASE_URL: str = Field(
        default="postgresql://postgres:postgres@db:5432/resume_tailorer",
        validation_alias="DATABASE_URL"
    )

    # --------------------------------------------------------------------------
    # AI Engine (Google Gemini)
    # --------------------------------------------------------------------------
    # The API key required to run Gemini queries. Server-side only (never exposed).
    GEMINI_API_KEY: str = Field(default="", validation_alias="GEMINI_API_KEY")
    
    # Gemini models used in our pipeline stages.
    GEMINI_MODEL: str = "gemini-2.5-flash"      # Default fast model (matching UI)
    GEMINI_PRO_MODEL: str = "gemini-2.5-pro"    # Reasoning model for hard queries

    # --------------------------------------------------------------------------
    # Security & Authentication
    # --------------------------------------------------------------------------
    # Secret key for encrypting and signing JWT (JSON Web Token) signatures.
    # CRITICAL: For production, override this with a high-entropy hex string
    # generated by running: openssl rand -hex 32
    JWT_SECRET_KEY: str = Field(
        default="09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7",
        validation_alias="JWT_SECRET_KEY"
    )
    
    # Encryption algorithm for token signatures
    JWT_ALGORITHM: str = "HS256"
    
    # Token lifespan. Default is 1440 minutes (24 hours)
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 1440

    # --------------------------------------------------------------------------
    # Tectonic Sandbox Compilation
    # --------------------------------------------------------------------------
    # The Docker image used to execute the 'tectonic' LaTeX compiler command
    # safely isolated from the main server environment.
    DOCKER_TECTONIC_IMAGE: str = "dxjoke/tectonic:latest"

    # --------------------------------------------------------------------------
    # Rate Limiting (SlowAPI)
    # --------------------------------------------------------------------------
    # Prevents brute force login attempts
    RATE_LIMIT_LOGIN: str = "5/minute"
    # Prevents API token overuse / cost spike on Gemini calls
    RATE_LIMIT_TAILOR: str = "20/hour"

    # --------------------------------------------------------------------------
    # Settings Loader Config
    # --------------------------------------------------------------------------
    # Configures Pydantic Settings to look for a '.env' file first.
    # Excludes variables not specified above to prevent configuration pollution.
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore"
    )

# Instantiate config instance to export globally
settings = Settings()
