# ==============================================================================
# LaTeX Resume Tailorer — Database Models
# ==============================================================================
# This module defines the schemas for our database tables using SQLAlchemy ORM.
# It also includes pgvector integration for storing 384-dimensional sentence
# embedding vectors from the 'all-MiniLM-L6-v2' model.
# ==============================================================================

from datetime import datetime
from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, Float, JSON
from sqlalchemy.orm import relationship
from pgvector.sqlalchemy import Vector

from backend.database import Base

class User(Base):
    """
    User account credentials and identity management.
    """
    __tablename__ = "users"

    id = Column(Integer, primary key=True, index=True)
    email = Column(String(255), unique=True, index=True, nullable=False)
    # Password stored as a secure bcrypt hash (never in plaintext)
    hashed_password = Column(String(255), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    # 'cascade="all, delete-orphan"' automatically deletes a user's resumes if
    # the user is deleted (GDPR / account termination compliance)
    resumes = relationship("Resume", back_populates="user", cascade="all, delete-orphan")
    audit_logs = relationship("AuditLog", back_populates="user", cascade="all, delete-orphan")

class Resume(Base):
    """
    Original user resume entries. Stores the LaTeX source and parsed AST.
    """
    __tablename__ = "resumes"

    id = Column(Integer, primary key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    title = Column(String(255), default="My Resume")
    raw_latex = Column(Text, nullable=False)
    # The JSON-parsed representation of the LaTeX (AST)
    parsed_ast = Column(JSON, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    user = relationship("User", back_populates="resumes")
    versions = relationship("Version", back_populates="resume", cascade="all, delete-orphan")
    bullet_vectors = relationship("ResumeBulletVector", back_populates="resume", cascade="all, delete-orphan")

class ResumeBulletVector(Base):
    """
    Vector embeddings table. Stores sentence-transformer embeddings (384 float
    dimensions) for every plain-text bullet point parsed from the LaTeX resume.
    This enables semantic similarity queries against job description requirements.
    """
    __tablename__ = "resume_bullet_vectors"

    id = Column(Integer, primary key=True, index=True)
    resume_id = Column(Integer, ForeignKey("resumes.id", ondelete="CASCADE"), nullable=False)
    section_id = Column(String(100), nullable=False)     # e.g., "section_0"
    bullet_index = Column(Integer, nullable=False)      # Position inside the section list
    bullet_text = Column(Text, nullable=False)          # Original plain-text string
    
    # pgvector embedding storage
    # 'all-MiniLM-L6-v2' outputs exactly 384 dimensions
    embedding = Column(Vector(384), nullable=False)

    # Relationships
    resume = relationship("Resume", back_populates="bullet_vectors")

class Version(Base):
    """
    Tailored outputs generated by the LLM tailoring engine.
    """
    __tablename__ = "versions"

    id = Column(Integer, primary key=True, index=True)
    resume_id = Column(Integer, ForeignKey("resumes.id", ondelete="CASCADE"), nullable=False)
    job_title = Column(String(255), nullable=False)
    tailored_latex = Column(Text, nullable=False)
    # Score estimations
    ats_score_before = Column(Float, nullable=False)
    ats_score_after = Column(Float, nullable=False)
    mode = Column(String(50), nullable=False)           # 'conservative' | 'moderate' | 'aggressive'
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    resume = relationship("Resume", back_populates="versions")
    feedbacks = relationship("Feedback", back_populates="version", cascade="all, delete-orphan")

class Feedback(Base):
    """
    User evaluation feedback (1-5 stars and optional reviews).
    """
    __tablename__ = "feedbacks"

    id = Column(Integer, primary key=True, index=True)
    version_id = Column(Integer, ForeignKey("versions.id", ondelete="CASCADE"), nullable=False)
    score_stars = Column(Integer, nullable=False)       # 1 to 5 rating
    thumbs_direction = Column(String(10), nullable=False) # 'up' | 'down'
    comments = Column(Text, default="")
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    version = relationship("Version", back_populates="feedbacks")

class AuditLog(Base):
    """
    Security and action tracking log.
    CRITICAL CONSTRAINT: To avoid storing sensitive personal identifiable
    information, this log only records metadata (action, timestamp, user reference)
    without logging full resume contents or PDF payloads.
    """
    __tablename__ = "audit_logs"

    id = Column(Integer, primary key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=True) # Null for pre-login actions
    action = Column(String(100), nullable=False)         # e.g., "login", "tailor_resume"
    ip_address = Column(String(45), nullable=True)       # IPv4 or IPv6 address length compliant
    timestamp = Column(DateTime, default=datetime.utcnow)

    # Relationships
    user = relationship("User", back_populates="audit_logs")
