# ==============================================================================
# LaTeX Resume Tailorer — Pydantic Validation Schemas
# ==============================================================================
# This module defines Pydantic v2 schemas for checking and validating JSON inputs
# sent by the client, and formatting outputs returned by the API.
# ==============================================================================

from datetime import datetime
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, EmailStr, Field, ConfigDict

# --------------------------------------------------------------------------
# Auth & User Schemas
# --------------------------------------------------------------------------

class UserRegister(BaseModel):
    """Payload sent during new user registration."""
    email: EmailStr = Field(..., description="User's email address")
    password: str = Field(..., min_length=8, description="Minimum 8-character password")

class UserLogin(BaseModel):
    """Payload sent during login request."""
    email: EmailStr
    password: str

class UserOut(BaseModel):
    """Response returned describing a user (never returns password hashes)."""
    id: int
    email: str
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)

class Token(BaseModel):
    """JWT response structure upon successful authentication."""
    access_token: str
    token_type: str = "bearer"

class TokenData(BaseModel):
    """Parsed data payload from a decrypted JWT."""
    email: Optional[str] = None

# --------------------------------------------------------------------------
# Resume & AST Schemas
# --------------------------------------------------------------------------

class ResumeCreate(BaseModel):
    """Input payload to create/upload a new resume."""
    title: str = "My Resume"
    raw_latex: str

class ResumeOut(BaseModel):
    """Database representation of an uploaded resume."""
    id: int
    user_id: int
    title: str
    created_at: datetime
    # We omit the full LaTeX and AST in listing queries to save bandwidth

    model_config = ConfigDict(from_attributes=True)

class ResumeDetailOut(BaseModel):
    """Complete detail output for a resume including the parsed AST structure."""
    id: int
    user_id: int
    title: str
    raw_latex: str
    parsed_ast: Dict[str, Any]
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)

# --------------------------------------------------------------------------
# Job Description (JD) Schemas
# --------------------------------------------------------------------------

class JDInput(BaseModel):
    """Raw text payload of the job description to analyze."""
    jd_text: str

class JDAnalysisOut(BaseModel):
    """Structured extraction of requirements from the JD."""
    role_title: str
    company_context: str
    experience_level: str
    required_skills: List[str]
    preferred_skills: List[str]
    soft_skills: List[str]
    industry_terms: List[str]
    ats_keywords: List[str]
    responsibilities: List[str]

# --------------------------------------------------------------------------
# Tailoring Execution Schemas
# --------------------------------------------------------------------------

class TailorConfig(BaseModel):
    """Configuration params for the AI tailoring run."""
    mode: str = "moderate" # 'conservative' | 'moderate' | 'aggressive'
    custom_instructions: str = ""

class TailorRequest(BaseModel):
    """Complete request payload to tailor a resume."""
    resume_id: int
    jd_analysis: JDAnalysisOut
    config: TailorConfig = Field(default_factory=TailorConfig)
    # List of section IDs to protect (e.g. ["section_0"])
    locked_section_ids: List[str] = Field(default_factory=list)

class ChangeLogEntry(BaseModel):
    """Describes a single bullet point edit suggested by the pipeline."""
    title: str
    type: str # 'skill' | 'metric' | 'keyword' | 'restructure'
    description: str
    oldText: str
    newText: str

class FabricationFlag(BaseModel):
    """Describes an entity flagged as potentially fabricated by our check."""
    entity: str
    type: str # 'tech' | 'metric' | 'proper_noun'
    context: str

class TailorCandidate(BaseModel):
    """One candidate variant generated by the multi-gen pipeline."""
    mode: str
    latex: str
    changes: List[ChangeLogEntry]
    fabrication_flags: List[FabricationFlag]
    reverted_sections: List[str]

class TailorResponse(BaseModel):
    """Output returned by the server containing candidate variants and scores."""
    version_id: int
    best_mode: str
    ats_score_before: int
    ats_score_after: int
    ats_score_min: int
    ats_score_max: int
    ats_method_note: str
    candidates: List[TailorCandidate]

# --------------------------------------------------------------------------
# Feedback & Version History Schemas
# --------------------------------------------------------------------------

class FeedbackCreate(BaseModel):
    """Input payload to record candidate rating feedback."""
    version_id: int
    score_stars: int = Field(..., ge=1, le=5)
    thumbs_direction: str = Field(..., pattern="^(up|down)$")
    comments: str = ""

class FeedbackOut(BaseModel):
    """Feedback record saved in PostgreSQL database."""
    id: int
    version_id: int
    score_stars: int
    thumbs_direction: str
    comments: str
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)

class VersionOut(BaseModel):
    """Database record for a tailored version history entry."""
    id: int
    resume_id: int
    job_title: str
    ats_score_before: float
    ats_score_after: float
    mode: str
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)
